### ISSUE TITLE
multi-face keyoint detection support

### ISSUE THREAD

**Issue by soans1994** [hellojialee/Multi-Person-Pose-using-Body-Parts#37]
hello author,

Does this repo has multi-face keyoint detection support?
I want to ask wheter the COCO person dataset is specialized for multi-person?
i have trained a simple model using FCN for face keypoint regression. Can you please tell me how we can get heatmaps of muliple faces in the bottom-up approach. My current model takes input of 96x96x1 image and gives 96x96x15 size heatmaps for 15 keypoints. I trained my model using kaggle datset consisting of images with single face pre cropped to 96x96. Do i need the dataset with multiple faces? and do I need bouding box information or mask information too?

Please give me your advice
thank you

**Comment by hellojialee** [comment]
Sorry, this repo does not support face landmark detection. Your could refer to MMPose repo that supports face keypoints. Maybe some useful info could be found there.
To some extent,  COCO person dataset considers the real-life scenarios in which multiple person may exist at the same time.

**Comment by soans1994** [comment]
thank you, can you please tell me easy implementation of paf with just 2 keypoints (for 1 limb). i am not able to undertand the code. Please guide me

**Comment by hellojialee** [comment]
Hi, this repo doesn't use the original PAF.  But here is an example to generate offset between two keypoints:

https://github.com/hellojialee/OffsetGuided/blob/211a9e0a560982b794ae93e165359670d27d03d9/encoder/offset.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L127

**Comment by soans1994** [comment]
@hellojialee 

thank you very much for your help. I will look into the code.

**Comment by soans1994** [comment]
Does the model learn features inside the traingle reigon (Jfrom, Jto and Joffset) and predict the output offsets? Is this the goal ?
DeltaL(error distance) similar to the PAF width?

**Comment by hellojialee** [comment]
A1: CNN is able to lean and infer the human skeleton structure. CNN infers the guiding offsets between adjacent keypoints.

A2: I didn't understand your question.

A3: No.

A4: Yes.
